### ISSUE TITLE
Heroku is not working!

### ISSUE THREAD

**Issue by tranlehaiquan** [huczk/realworld-ts-gql#3]
Heroku is not working. Please check.
(This project is so good : D, I'm try to build one, not exact same)

**Comment by docrob0t** [comment]
Just wondering if @huczk is still working on this project? Are you planning to merge it with the realworld app repo?

**Comment by huczk** [comment]
The issue I made on realworld repo was closed because they preparing v2. My repo will be deprecated then. For now im not having plans to update it to v2
